name=input("enter your name:")
age=int(input("enter your age:"))
height=float(input("enter your height:"))
print(f"my name is {name} and i am {age} years old and my height is {height} feet.")
value1=int(input("enter your value1:"))
value2=int(input("enter your value2:"))
print(f"sum of two numbers:{value1+value2}")
print(f"difference of two numbers:{value1-value2}")
print(f"product of two numbers:{value1*value2}")
print(f"quotient of two numbers:{value1/value2}")